# Generated by Django 2.2.4 on 2019-09-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='identity_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
