# Generated by Django 2.2.4 on 2019-10-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_vehicle_identity_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletype',
            name='driver_salary',
        ),
        migrations.RemoveField(
            model_name='vehicletype',
            name='helper_salary',
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='cng_limit_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='octane_limit_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AddField(
            model_name='vehicletype',
            name='petrol_limit_per_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
