# Generated by Django 2.2.4 on 2019-10-01 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entries', '0004_auto_20191001_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicing_date', models.DateTimeField(blank=True, null=True)),
                ('expire_date', models.DateTimeField(blank=True, null=True)),
                ('expire_km', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('workshop', models.CharField(blank=True, max_length=100, null=True)),
                ('service_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.ServiceName')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PostKmAllowence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('expense_date', models.DateField(auto_now=True, null=True)),
                ('starting_km', models.DecimalField(decimal_places=2, max_digits=20)),
                ('ending_km', models.DecimalField(decimal_places=2, max_digits=20)),
                ('octane_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('petrol_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cng_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Driver')),
                ('helper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.Helper')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entries.Vehicle')),
            ],
        ),
    ]
