# Generated by Django 2.2.4 on 2019-10-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0006_holiday_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.DateField(blank=True, null=True),
        ),
    ]
