# Generated by Django 2.2.4 on 2019-10-05 05:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_auto_20191005_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postkmallowence',
            name='expense_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
