# Generated by Django 2.2.5 on 2019-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0008_auto_20191005_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='expire_date',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='expire_km',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='service_charge',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='servicing_date',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='workshop',
        ),
        migrations.AddField(
            model_name='setting',
            name='approved_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='company_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='days_in_month',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='dinner_time_ends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='dinner_time_starts',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='lunch_time_ends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='lunch_time_starts',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='minimum_hrs_count_as_say',
            field=models.PositiveIntegerField(blank=True, default=8, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='recomended_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='work_time_ends',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='work_time_starts',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
